---
- name: Infra AWS Web Dev Lab
  hosts: localhost
  roles:
    - infra

- name: Refresh inventory to ensure new instances are available
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for AWS API consistency
      pause:
        seconds: 15
    - name: Refresh inventory
      meta: refresh_inventory

- name: Configure Database servers
  hosts: tag_Role_DB
  gather_facts: no
  vars:
    bastion_host: "{{ hostvars[groups['tag_Role_Bastion'][0]].ansible_host }}"
  pre_tasks:
    - name: Wait for bastion to be available
      wait_for:
        host: "{{ bastion_host }}"
        port: 22
        timeout: 300
        state: started
      delegate_to: localhost

    - name: Wait for DB instance SSH to be available through bastion
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 300
        state: started
      delegate_to: "{{ bastion_host }}"

  roles:
    - database

- name: Configure Web servers
  hosts: tag_Role_Web
  gather_facts: no
  vars:
    bastion_host: "{{ hostvars[groups['tag_Role_Bastion'][0]].ansible_host }}"
  pre_tasks:
    - name: Wait for Web instance SSH to be available through bastion
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 300
        state: started
      delegate_to: "{{ bastion_host }}"

  roles:
    - webserver
    - phpmyadmin

- name: Configure Bastion servers
  hosts: tag_Role_Bastion
  gather_facts: no
  roles:
    - bastion
