---
- name: Infra AWS Web Dev Lab
  hosts: localhost
  roles:
    - infra

- name: Refresh inventory to ensure new instances are available
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for AWS API consistency
      pause:
        seconds: 15
    - name: Refresh inventory
      meta: refresh_inventory

- name: Configure Database servers
  hosts: tag_Role_DB
  gather_facts: no
  roles:
    - database

- name: Configure Web servers
  hosts: tag_Role_Web
  gather_facts: no
  roles:
    - webserver

- name: Configure Bastion servers
  hosts: tag_Role_Bastion
  gather_facts: no
  roles:
    - bastion
