---
- name: Infra AWS Web Dev Lab
  hosts: localhost
  gather_facts: yes
  roles:
    - infra

- name: Refresh inventory to ensure new instances are available
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for AWS API consistency
      pause:
        seconds: 15
    - name: Refresh inventory
      meta: refresh_inventory

- name: Configure Bastion host
  hosts: tag_Role_Bastion
  become: yes
  gather_facts: yes
  roles:
    - bastion

- name: Wait for SSH service to stabilize
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause for SSH restart
      pause:
        seconds: 10
      when: "'tag_Role_Bastion' in groups"
    - name: Pause to let AWS infrastructure settle
      pause:
        seconds: 5
      when: "'tag_Role_Bastion' in groups"
    - name: Clear dynamic inventory cache
      ansible.builtin.file:
        path: ~/.ansible/tmp/ansible-ec2-*.cache
        state: absent
      when: "'tag_Role_Bastion' in groups"
    - name: Refresh inventory after bastion configuration
      meta: refresh_inventory

- name: Configure Database servers
  hosts: tag_Role_DB
  become: yes
  gather_facts: yes
  roles:
    - database

- name: Configure Web servers
  hosts: tag_Role_Web
  become: yes
  gather_facts: yes
  roles:
    - webserver
