---
- name: Infra AWS Web Dev Lab
  hosts: localhost
  gather_facts: yes  # Important d'avoir les facts pour localhost
  roles:
    - infra

- name: Refresh inventory to ensure new instances are available
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for AWS API consistency
      pause:
        seconds: 15
    - name: Refresh inventory
      meta: refresh_inventory

- name: Configure Bastion host
  hosts: tag_Role_Bastion
  become: yes
  gather_facts: yes  # Important d'avoir les facts pour la config SSH
  roles:
    - bastion

- name: Configure Database servers
  hosts: tag_Role_DB
  become: yes
  gather_facts: yes  # Important d'avoir les facts pour la config réseau
  roles:
    - database

- name: Configure Web servers
  hosts: tag_Role_Web
  become: yes
  gather_facts: yes  # Important d'avoir les facts pour la config réseau
  roles:
    - webserver
