- name: Infra AWS Web Dev Lab
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: infra
      tags: [infra]

- name: Refresh inventory to ensure new instances are available
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for AWS API consistency
      pause:
        seconds: 15
      when: infra_state == "present"
      tags: [infra]

    - name: Refresh inventory
      meta: refresh_inventory
      tags: [infra]

- name: Configure Database servers
  hosts: tag_Role_DB
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no 
      -o UserKnownHostsFile=/dev/null 
      -o ProxyCommand="ssh -q -W %h:%p -i {{ ansible_ssh_private_key_file }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ hostvars[groups['tag_Role_Bastion'][0]].public_ip_address }}"
  pre_tasks:
    - name: Wait for SSH to become available on DB server
      wait_for:
        host: "{{ hostvars[inventory_hostname].private_ip_address }}"
        port: 22
        timeout: 300
        connect_timeout: 5
        delay: 10
        search_regex: OpenSSH
      delegate_to: "{{ hostvars[groups['tag_Role_Bastion'][0]].public_ip_address }}"
      remote_user: "{{ ansible_user }}"

    - name: Test SSH connection through bastion
      command: "hostname"
      changed_when: false
      register: hostname_test

    - name: Gather facts
      setup:
  roles:
    - role: database
      tags: [db]
    - role: phpmyadmin
      tags: [phpmyadmin]

- name: Configure Web servers
  hosts: tag_Role_Web
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no 
      -o UserKnownHostsFile=/dev/null 
      -o ProxyCommand="ssh -q -W %h:%p -i {{ ansible_ssh_private_key_file }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ hostvars[groups['tag_Role_Bastion'][0]].public_ip_address }}"
  pre_tasks:
    - name: Wait for SSH to become available on Web server
      wait_for:
        host: "{{ hostvars[inventory_hostname].private_ip_address }}"
        port: 22
        timeout: 300
        connect_timeout: 5
        delay: 10
        search_regex: OpenSSH
      delegate_to: "{{ hostvars[groups['tag_Role_Bastion'][0]].public_ip_address }}"
      remote_user: "{{ ansible_user }}"

    - name: Test SSH connection through bastion
      command: "hostname"
      changed_when: false
      register: hostname_test

    - name: Gather facts
      setup:
  roles:
    - role: webserver
      tags: [web]

- name: Configure Bastion servers
  hosts: tag_Role_Bastion
  become: yes
  gather_facts: yes
  roles:
    - role: bastion
      tags: [bastion]
