---
- name: Infra AWS Web Dev Lab
  hosts: localhost
  roles:
    - infra

- name: Refresh inventory to ensure new instances are available
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for AWS API consistency
      pause:
        seconds: 15
    - name: Refresh inventory
      meta: refresh_inventory

- name: Configure Database servers
  hosts: tag_Role_DB
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: /home/admin/.ssh/labsuser.pem
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i /home/admin/.ssh/labsuser.pem admin@{{ hostvars[groups[\"tag_Role_Bastion\"][0]].public_ip_address }}"'
  roles:
    - database

- name: Configure Web servers
  hosts: tag_Role_Web
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: /home/admin/.ssh/labsuser.pem
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i /home/admin/.ssh/labsuser.pem admin@{{ hostvars[groups[\"tag_Role_Bastion\"][0]].public_ip_address }}"'
  roles:
    - webserver

- name: Configure Bastion servers
  hosts: tag_Role_Bastion
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: /home/admin/.ssh/labsuser.pem
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  roles:
    - bastion
